version: '3.4'

services:
  mongodb:
    image: mongo:4
    restart: always
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
      - '9001:9001'
    # volumes:
    #   - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    #   - ./mosquitto/data:/mosquitto/data
    #   - ./mosquitto/log:/mosquitto/log
    restart: always
  node_app:
    build: .
    depends_on:
      - mongodb
      - mosquitto
    environment:
      - MQTT_PORT=1883
      - MQTT_PROTOCOL=mqtt
      - MQTT_HOST=mosquitto
      - MQTT_CLIENT_NAME=homie-iot-mongodb.ts
      - MONGODB_HOST=mongodb
    tty: true
