version: '3.4'

services:
  mongodb:
    image: mongo:4
    restart: always
  mqtt_server:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
      - '9001:9001'
    # volumes:
    #   - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    #   - ./mosquitto/data:/mosquitto/data
    #   - ./mosquitto/log:/mosquitto/log
    restart: always
  node_app:
    image: node:dubnium-alpine
    depends_on:
      - mongodb
      - mqtt_server
    environment:
      - MQTT_PORT=1883
      - MQTT_PROTOCOL=mqtt
      - MQTT_HOST=mqtt_server
      - MQTT_CLIENT_NAME=homie-iot-mongodb.ts_dev
      - MONGODB_HOST=mongodb
    tty: true
    working_dir: /homie-iot-mongodb.ts
    volumes:
      - 'node_modules:/homie-iot-mongodb.ts/node_modules'
      - './docker/node_modules/:/homie-iot-mongodb.ts/node_modules'
      - './scripts/installAndWatchDev.sh:/homie-iot-mongodb.ts/installAndWatchDev.sh'
      - './src/:/homie-iot-mongodb.ts/src'
      - './nodemon.json:/homie-iot-mongodb.ts/nodemon.json'
      - './package.json:/homie-iot-mongodb.ts/package.json'
      - './tsconfig.json:/homie-iot-mongodb.ts/tsconfig.json'
      - './yarn.lock:/homie-iot-mongodb.ts/yarn.lock'
    command: ['/bin/sh', './installAndWatchDev.sh']

volumes:
  node_modules:
