version: '3.4'

services:
  mongodb:
    image: mongo:4
    restart: always
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
  node_app:
    image: node:dubnium-alpine
    depends_on:
      - mongodb
      - mosquitto
    environment:
      - MQTT_PORT=1883
      - MQTT_PROTOCOL=mqtt
      - MQTT_HOST=mosquitto
      - MQTT_CLIENT_NAME=homie-iot-mongodb.ts_test
      - MONGODB_HOST=mongodb
    stdin_open: true
    tty: true
    working_dir: /homie-iot-mongodb.ts
    volumes:
      - 'node_modules:/homie-iot-mongodb.ts/node_modules'
      - './scripts/installAndTest.sh:/homie-iot-mongodb.ts/installAndTest.sh'
      - './src/:/homie-iot-mongodb.ts/src'
      - './jest.config.js:/homie-iot-mongodb.ts/jest.config.js'
      - './package.json:/homie-iot-mongodb.ts/package.json'
      - './tsconfig.json:/homie-iot-mongodb.ts/tsconfig.json'
      - './yarn.lock:/homie-iot-mongodb.ts/yarn.lock'
    entrypoint: ['/bin/sh']

volumes:
  node_modules:
