version: '3'

services:
  mqtt_logger:
    build: .
    depends_on:
      - mqtt_server
    environment:
      - MQTT_PORT=1883
      - MQTT_PROTOCOL=mqtt
      - MQTT_HOST=localhost
      - MQTT_CLIENT_NAME=mqtt_logger
    tty: true
